---
- name: Deploy WordPress on LXC container
  hosts: all
  become: true
  vars:
    mysql_root_password: "{{ lookup('password', '/tmp/mysql_root_password length=20') }}"
    mysql_db: wordpress
    mysql_user: wordpress
    mysql_password: "{{ lookup('password', '/tmp/mysql_wordpress_password length=20') }}"
    wordpress_version: "6.4.3"
    wordpress_url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
    wordpress_path: "/var/www/html/wordpress"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apache2
          - mariadb-server
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - wget
          - unzip
          - python3-pymysql
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Set MariaDB root password
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

    - name: Create WordPress database
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create WordPress database user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Download WordPress
      get_url:
        url: "{{ wordpress_url }}"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extract WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html"
        remote_src: yes

    - name: Set WordPress directory permissions
      file:
        path: "{{ wordpress_path }}"
        state: directory
        mode: '0755'
        recurse: yes

    - name: Create wp-config.php
      template:
        src: wp-config.php.j2
        dest: "{{ wordpress_path }}/wp-config.php"
        mode: '0644'

    - name: Configure Apache for WordPress
      template:
        src: wordpress.conf.j2
        dest: /etc/apache2/sites-available/wordpress.conf
        mode: '0644'

    - name: Enable WordPress site
      file:
        src: /etc/apache2/sites-available/wordpress.conf
        dest: /etc/apache2/sites-enabled/wordpress.conf
        state: link

    - name: Enable required Apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - rewrite
        - headers

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
