---
- name: Install Apache2 package
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Enable Apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - http2
  notify: restart apache2

- name: Ensure Apache2 is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes
